// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUM3QFEnV_ugiJQnJDivzViBKkUvNwEnY',
    appId: '1:837683672156:web:4d91b3d1fecc628cb9a299',
    messagingSenderId: '837683672156',
    projectId: 'fir-firebase-codelab',
    authDomain: 'fir-firebase-codelab.firebaseapp.com',
    storageBucket: 'fir-firebase-codelab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6MAF_g834r-PZ-0zFAASo80cZj7-FlMc',
    appId: '1:837683672156:android:7746a1420350cdb3b9a299',
    messagingSenderId: '837683672156',
    projectId: 'fir-firebase-codelab',
    storageBucket: 'fir-firebase-codelab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxJwUuI6ntk0t-AMmoINCfFtb5RyWgiyE',
    appId: '1:837683672156:ios:44d69f1e2843ae55b9a299',
    messagingSenderId: '837683672156',
    projectId: 'fir-firebase-codelab',
    storageBucket: 'fir-firebase-codelab.appspot.com',
    iosClientId: '837683672156-t82anm012g6u8oskb0nqscrft26fcelh.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxJwUuI6ntk0t-AMmoINCfFtb5RyWgiyE',
    appId: '1:837683672156:ios:44d69f1e2843ae55b9a299',
    messagingSenderId: '837683672156',
    projectId: 'fir-firebase-codelab',
    storageBucket: 'fir-firebase-codelab.appspot.com',
    iosClientId: '837683672156-t82anm012g6u8oskb0nqscrft26fcelh.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
